# Generated by Django 6.0.5 on 2026-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MAIN_PASTOR", "Main Pastor"),
                    ("ASSISTANT_PASTOR", "Assistant Pastor"),
                    ("CONGREGATION_ELDER", "Congregation Elder"),
                    ("ADMIN", "Administrator"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("AUDITOR", "Auditor"),
                    ("MEMBER", "Member"),
                ],
                max_length=30,
            ),
        ),
    ]
