# Generated by Django 6.0.5 on 2026-10-02 10:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, upload_to=users.models.profile_picture_path
            ),
        ),
    ]
