# Generated by Django 6.0.5 on 2026-10-10 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_user_public_ids(apps, schema_editor):
    user_model = apps.get_model('users', 'User')
    for user in user_model.objects.filter(public_id__isnull=True).iterator():
        user.public_id = uuid.uuid4()
        user.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_user_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ApiTokenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('access_token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('installation_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_token_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='users_apito_user_id_378295_idx'), models.Index(fields=['refresh_expires_at'], name='users_apito_refresh_2a434f_idx')],
            },
        ),
    ]
