# Generated by Django 6.0.5 on 2026-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('PASSWORD_RESET', 'Password Reset'), ('MEMBER_CREATED', 'Member Created'), ('MEMBER_APPROVED', 'Member Approved'), ('MEMBER_REJECTED', 'Member Rejected'), ('EXCEL_UPLOADED', 'Excel Uploaded'), ('EXCEL_APPROVED', 'Excel Approved'), ('CONTRIBUTION_CREATED', 'Contribution Created'), ('TARGET_UPDATED', 'Target Updated'), ('CHURCH_UPDATED', 'Church Updated'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_UPDATED', 'Profile Updated'), ('DEVICE_REGISTERED', 'Device Registered'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
