# Generated by Django 6.0.5 on 2026-05-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contribution_weeks", "0001_initial"),
        ("financial_years", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionweek",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="financial_years.financialyear",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributionweek",
            unique_together={("church", "financial_year", "week_number")},
        ),
    ]
