# Generated by Django 6.0.5 on 2026-10-04 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_contributioncategory_options_and_more"),
        ("churches", "0001_initial"),
        ("contribution_weeks", "0002_initial"),
        ("contributions", "0001_initial"),
        ("financial_years", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="contribution_amount_positive",
            ),
        ),
    ]
