# Generated by Django 6.0.5 on 2026-10-10 09:36

import uuid
from django.db import migrations, models


def populate_public_ids(apps, schema_editor):
    model = apps.get_model('contributions', 'Contribution')
    for instance in model.objects.filter(public_id__isnull=True).iterator():
        instance.public_id = uuid.uuid4()
        instance.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_contribution_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contribution',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
