# Generated by Django 6.0.5 on 2026-10-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0002_contribution_contribution_amount_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="source",
            field=models.CharField(
                choices=[
                    ("EXCEL_UPLOAD", "Contribution Upload"),
                    ("MANUAL_ENTRY", "Manual Entry"),
                    ("ONLINE_PAYMENT", "Online Payment"),
                    ("CORRECTION", "Correction"),
                ],
                max_length=30,
            ),
        ),
    ]
