# Generated by Django 6.0.5 on 2026-05-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jumuiya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jumuiya",
                        to="churches.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jumuiya",
                "verbose_name_plural": "Jumuiya",
                "ordering": ["name"],
                "unique_together": {("church", "name")},
            },
        ),
    ]
