# Generated by Django 6.0.5 on 2026-05-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contributioncategory",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Contribution Category",
                "verbose_name_plural": "Contribution Categories",
            },
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="display_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="is_annual",
            field=models.BooleanField(default=False),
        ),
    ]
