# Generated by Django 6.0.5 on 2026-05-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("churches", "0001_initial"),
        ("contribution_weeks", "0002_initial"),
        ("financial_years", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel_uploads/")),
                ("file_name", models.CharField(max_length=255)),
                ("upload_reference", models.CharField(max_length=100, unique=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VALIDATION", "Pending Validation"),
                            ("VALIDATED", "Validated"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING_VALIDATION",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_excel_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to="churches.church",
                    ),
                ),
                (
                    "contribution_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to="contribution_weeks.contributionweek",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to="financial_years.financialyear",
                    ),
                ),
                (
                    "selected_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_uploads",
                        to="categories.contributioncategory",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excel_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Excel Upload",
                "verbose_name_plural": "Excel Uploads",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExcelUploadRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("bahasha_number", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[("VALID", "Valid"), ("INVALID", "Invalid")],
                        default="INVALID",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excel_upload_rows",
                        to="members.member",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="excel_uploads.excelupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excel Upload Row",
                "verbose_name_plural": "Excel Upload Rows",
                "ordering": ["row_number"],
            },
        ),
    ]
