# Generated by Django 6.0.5 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("churches", "0002_churchgroup"),
        ("members", "0002_alter_member_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="church_groups",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="churches.churchgroup"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE", "Single"),
                    ("MARRIED", "Married"),
                    ("SEPARATED", "Separated"),
                    ("DIVORCED", "Divorced"),
                    ("WIDOWED", "Widowed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
