# Generated by Django 6.0.5 on 2026-10-10 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_notification_public_ids(apps, schema_editor):
    notification_model = apps.get_model('notifications', 'Notification')
    for notification in notification_model.objects.filter(
        public_id__isnull=True
    ).iterator():
        notification.public_id = uuid.uuid4()
        notification.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='public_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_notification_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='notification',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installation_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('push_token', models.CharField(max_length=512)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'installation_id'), name='unique_mobile_installation_per_user')],
            },
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='unique_notification_receipt_per_user')],
            },
        ),
    ]
